//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EHealth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.RecipeFoodAssignments = new HashSet<RecipeFoodAssignment>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> Calories { get; set; }
        public Nullable<double> Carbohidrates { get; set; }
        public Nullable<double> Sugar { get; set; }
        public Nullable<double> Fiber { get; set; }
        public Nullable<double> Fats { get; set; }
        public Nullable<double> Proteins { get; set; }
        public string PictureUrl { get; set; }
        public int Grams { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeFoodAssignment> RecipeFoodAssignments { get; set; }
    }
}
