//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EHealth
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeFoodAssignment
    {
        public System.Guid RecipeId { get; set; }
        public System.Guid FoodId { get; set; }
        public double Quantity { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
